{{- if .Values.embedded }}
apiVersion: v1
kind: Secret
metadata:
  name: gigapipe-clickhouse
  labels:
    app: gigapipe-clickhouse
    release: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
{{- end }}
