{{- if .Values.embedded }}
apiVersion: v1
kind: Service
metadata:
  name: gigapipe-clickhouse
  labels:
    app: gigapipe-clickhouse
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gigapipe-clickhouse
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      name: tcp
{{- end }}
